// Copyright (C) 2026 Michael Wilson <mike@mdwn.dev>
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, version 3.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.
//
//! Synthesizes an mtrack project directory on disk from detected hardware.
//!
//! Configs are rendered as YAML text rather than built from `config` structs on
//! purpose: the suite should exercise the same parse path a user's hand-written
//! file takes, including the defaults and normalization that only run on
//! deserialization.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::net::TcpListener;
use std::path::{Path, PathBuf};

use tempfile::TempDir;

use crate::capabilities::Capabilities;
use crate::songs::SongSpec;

/// Venue the generated lighting config selects.
pub const VENUE_NAME: &str = "e2e_venue";

/// Logical group that generated shows address.
pub const LIGHTING_GROUP: &str = "e2e_wash";

/// Fixture type the generated venue patches.
const FIXTURE_TYPE: &str = "E2E_Par";

/// How a profile should describe each hardware subsystem. Cases vary these to
/// exercise presence, absence, and misconfiguration.
#[derive(Debug, Clone)]
pub enum Subsystem {
    /// Configure the subsystem against real detected hardware.
    Detected,
    /// Omit the subsystem from the profile entirely.
    Absent,
    /// Point the subsystem at a device name that does not exist, to check that
    /// mtrack degrades rather than panics.
    Bogus(String),
    /// Use a specific device, e.g. the port discovery proved loops back.
    Named(String),
}

impl Subsystem {
    fn is_absent(&self) -> bool {
        matches!(self, Subsystem::Absent)
    }
}

/// A hardware profile to render into the project.
#[derive(Debug, Clone)]
pub struct ProfileSpec {
    pub name: String,
    pub hostname: Option<String>,
    pub audio: Subsystem,
    pub midi: Subsystem,
    pub dmx: Subsystem,
    /// Track name to output channel list. Empty means "derive from the songs".
    pub track_mappings: BTreeMap<String, Vec<u16>>,
    /// Extra `midi:` keys, e.g. `beat_clock: true`.
    pub midi_extra: BTreeMap<String, String>,
    /// Whether to emit a `dmx.lighting` block referencing the generated venue.
    pub lighting: bool,
}

impl ProfileSpec {
    /// A profile that uses whatever hardware was detected.
    pub fn detected(name: &str) -> ProfileSpec {
        ProfileSpec {
            name: name.to_string(),
            hostname: None,
            audio: Subsystem::Detected,
            midi: Subsystem::Detected,
            dmx: Subsystem::Detected,
            track_mappings: BTreeMap::new(),
            midi_extra: BTreeMap::new(),
            lighting: false,
        }
    }

    /// Sets a `midi:` key such as `beat_clock`.
    pub fn with_midi_key(mut self, key: &str, value: &str) -> ProfileSpec {
        self.midi_extra.insert(key.to_string(), value.to_string());
        self
    }

    /// Emits a `dmx.lighting` block wired to the generated venue.
    pub fn with_lighting(mut self) -> ProfileSpec {
        self.lighting = true;
        self
    }

    /// Renders the profile as YAML.
    fn render(&self, caps: &Capabilities, songs: &[SongSpec], grpc_port: u16) -> String {
        let mut out = String::new();
        out.push_str("# Generated by the mtrack hardware e2e suite.\n");
        out.push_str("kind: hardware_profile\n");
        if let Some(hostname) = &self.hostname {
            let _ = writeln!(out, "hostname: \"{hostname}\"");
        }

        self.render_audio(&mut out, caps, songs);
        self.render_midi(&mut out, caps);
        self.render_dmx(&mut out, caps);

        // Controllers belong to the profile: when `profiles` is present mtrack
        // ignores top-level `controller`/`controllers` entirely. Every profile
        // gets the gRPC controller so the suite keeps its control channel when
        // a case switches the active profile.
        out.push_str("controllers:\n");
        out.push_str("  - kind: grpc\n");
        let _ = writeln!(out, "    port: {grpc_port}");

        out
    }

    fn render_audio(&self, out: &mut String, caps: &Capabilities, songs: &[SongSpec]) {
        let device = match &self.audio {
            Subsystem::Absent => return,
            Subsystem::Bogus(name) | Subsystem::Named(name) => name.clone(),
            Subsystem::Detected => match &caps.audio_out {
                Some(d) => d.name.clone(),
                None => return,
            },
        };

        let channels = caps
            .audio_out
            .as_ref()
            .map(|d| d.max_channels)
            .unwrap_or(2)
            .max(2);

        out.push_str("audio:\n");
        let _ = writeln!(out, "  device: \"{}\"", escape(&device));

        // mtrack defaults to 44100, which plenty of interfaces do not offer --
        // digital consoles are commonly 48k-only. Pin the rate to something the
        // device actually reports so the generated project is openable rather
        // than failing for a reason that has nothing to do with what is being
        // tested.
        // Only a raw device reports the interface's real rates. A plug device
        // advertises whatever the plug layer can convert to -- it will happily
        // claim 44100 for hardware that is 48k-only -- so pinning from it would
        // be pinning to a fiction.
        if let Some(detected) = caps
            .audio_out
            .as_ref()
            .filter(|d| d.name.contains("hw:CARD=") && !d.name.contains("plughw:"))
        {
            let rates = &detected.sample_rates;
            if !rates.is_empty() && !rates.contains(&44_100) {
                // Prefer 48k, else the highest on offer. Taking the lowest
                // would happily pin an 8000 Hz device, which is below Nyquist
                // for five of the eight diagnostic tones -- the routing checks
                // would then fail for a reason we created.
                let chosen = if rates.contains(&48_000) {
                    48_000
                } else {
                    rates.iter().copied().max().unwrap_or(48_000)
                };
                let _ = writeln!(out, "  sample_rate: {chosen}");
            }
        }

        out.push_str("  track_mappings:\n");

        let mappings = if self.track_mappings.is_empty() {
            derive_track_mappings(songs, channels)
        } else {
            self.track_mappings.clone()
        };
        for (track, chans) in &mappings {
            let list = chans
                .iter()
                .map(|c| c.to_string())
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "    \"{}\": [{}]", escape(track), list);
        }
    }

    fn render_midi(&self, out: &mut String, caps: &Capabilities) {
        let device = match &self.midi {
            Subsystem::Absent => return,
            Subsystem::Bogus(name) | Subsystem::Named(name) => name.clone(),
            Subsystem::Detected => match &caps.midi_out {
                Some(d) => d.name.clone(),
                None => return,
            },
        };

        out.push_str("midi:\n");
        let _ = writeln!(out, "  device: \"{}\"", escape(&device));
        for (key, value) in &self.midi_extra {
            let _ = writeln!(out, "  {key}: {value}");
        }
    }

    fn render_dmx(&self, out: &mut String, caps: &Capabilities) {
        if self.dmx.is_absent() {
            return;
        }

        out.push_str("dmx:\n");
        match caps.ola_port {
            Some(port) => {
                let _ = writeln!(out, "  ola_port: {port}");
            }
            // Without a daemon the engine still runs, so lighting timelines and
            // effect state stay testable; only the wire output is unverified.
            None => out.push_str("  null_client: true\n"),
        }
        out.push_str("  universes:\n");
        out.push_str("    - universe: 1\n");
        out.push_str("      name: \"main\"\n");

        if !self.lighting {
            return;
        }

        // The group name here is what generated shows address. Constraints are
        // deliberately loose (one tag, one fixture minimum) so the venue
        // resolves on any rig.
        out.push_str("  lighting:\n");
        let _ = writeln!(out, "    current_venue: \"{VENUE_NAME}\"");
        out.push_str("    directories:\n");
        out.push_str("      fixture_types: lighting/fixture_types\n");
        out.push_str("      venues: lighting/venues\n");
        out.push_str("    groups:\n");
        let _ = writeln!(out, "      {LIGHTING_GROUP}:");
        let _ = writeln!(out, "        name: \"{LIGHTING_GROUP}\"");
        out.push_str("        constraints:\n");
        out.push_str("          - AllOf: [\"wash\"]\n");
        out.push_str("          - MinCount: 1\n");
    }
}

/// Spreads tracks across the available output channels so that each track
/// lands somewhere distinct where the interface allows it. This is what the
/// loopback routing check verifies.
fn derive_track_mappings(songs: &[SongSpec], channels: u16) -> BTreeMap<String, Vec<u16>> {
    let mut mappings = BTreeMap::new();
    let mut next = 1u16;
    for song in songs {
        for track in &song.tracks {
            mappings.entry(track.name.clone()).or_insert_with(|| {
                let channel = next;
                next = next % channels + 1;
                vec![channel]
            });
        }
    }
    mappings
}

/// Escapes a device name for a double-quoted YAML scalar. Device names on ALSA
/// routinely contain quotes and backslashes.
fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

/// A project directory the suite can start mtrack against.
pub struct Project {
    /// Kept alive so the directory outlives the test; dropped on teardown.
    _dir: TempDir,
    root: PathBuf,
    grpc_port: u16,
    web_port: u16,
    songs: Vec<SongSpec>,
}

impl Project {
    pub fn root(&self) -> &Path {
        &self.root
    }

    pub fn config_path(&self) -> PathBuf {
        self.root.join("mtrack.yaml")
    }

    pub fn grpc_port(&self) -> u16 {
        self.grpc_port
    }

    pub fn web_port(&self) -> u16 {
        self.web_port
    }

    pub fn songs(&self) -> &[SongSpec] {
        &self.songs
    }

    /// Reads a profile file back from disk. Used by persistence checks that
    /// need to prove a change reached the YAML, not just the running process.
    pub fn read_profile(&self, name: &str) -> std::io::Result<String> {
        std::fs::read_to_string(self.root.join("profiles").join(format!("{name}.yaml")))
    }

    /// Reads `mtrack.yaml` back from disk.
    pub fn read_config(&self) -> std::io::Result<String> {
        std::fs::read_to_string(self.config_path())
    }

    /// Every YAML file in the project, for diagnosing a setting that persisted
    /// somewhere other than where it was expected. "It didn't reach this file"
    /// and "it reached no file at all" are different bugs.
    pub fn dump_yaml(&self) -> String {
        let mut out = String::new();
        let mut paths = vec![self.config_path()];
        for dir in ["profiles", "playlists"] {
            if let Ok(entries) = std::fs::read_dir(self.root.join(dir)) {
                paths.extend(entries.flatten().map(|e| e.path()));
            }
        }

        for path in paths {
            let display = path
                .strip_prefix(&self.root)
                .unwrap_or(&path)
                .display()
                .to_string();
            match std::fs::read_to_string(&path) {
                Ok(body) => out.push_str(&format!("\n--- {display} ---\n{body}")),
                Err(e) => out.push_str(&format!("\n--- {display} (unreadable: {e}) ---\n")),
            }
        }
        out
    }
}

/// Builds a project directory.
pub struct ProjectBuilder {
    profiles: Vec<ProfileSpec>,
    songs: Vec<SongSpec>,
    playlist: Vec<String>,
    extra_config: BTreeMap<String, String>,
}

impl ProjectBuilder {
    pub fn new() -> ProjectBuilder {
        ProjectBuilder {
            profiles: vec![ProfileSpec::detected("01-e2e")],
            songs: Vec::new(),
            playlist: Vec::new(),
            extra_config: BTreeMap::new(),
        }
    }

    /// Replaces the profile list.
    pub fn profiles(mut self, profiles: Vec<ProfileSpec>) -> ProjectBuilder {
        self.profiles = profiles;
        self
    }

    /// Sets the songs to generate. The playlist defaults to all of them in
    /// order unless overridden.
    pub fn songs(mut self, songs: Vec<SongSpec>) -> ProjectBuilder {
        self.songs = songs;
        self
    }

    /// Overrides the playlist contents.
    /// Name of the second generated playlist, usable as a persistence target.
    pub const ALTERNATE_PLAYLIST: &'static str = "alternate";

    pub fn playlist(mut self, names: Vec<String>) -> ProjectBuilder {
        self.playlist = names;
        self
    }

    /// Sets a top-level `mtrack.yaml` key.
    pub fn config_key(mut self, key: &str, value: &str) -> ProjectBuilder {
        self.extra_config.insert(key.to_string(), value.to_string());
        self
    }

    /// Writes the project to a fresh temporary directory.
    pub fn build(self) -> Result<Project, Box<dyn std::error::Error>> {
        let caps = Capabilities::get();
        let dir = TempDir::with_prefix("mtrack-hw-e2e-")?;
        let root = dir.path().to_path_buf();

        std::fs::create_dir_all(root.join("songs"))?;
        std::fs::create_dir_all(root.join("profiles"))?;
        std::fs::create_dir_all(root.join("playlists"))?;

        for song in &self.songs {
            song.write(&root.join("songs"))?;
        }

        let (grpc_port, web_port) = free_port_pair()?;

        if self.profiles.iter().any(|p| p.lighting) {
            write_lighting_definitions(&root)?;
        }

        for profile in &self.profiles {
            let yaml = profile.render(caps, &self.songs, grpc_port);
            std::fs::write(
                root.join("profiles").join(format!("{}.yaml", profile.name)),
                yaml,
            )?;
        }

        let playlist_names = if self.playlist.is_empty() {
            self.songs.iter().map(|s| s.name.clone()).collect()
        } else {
            self.playlist.clone()
        };
        let mut playlist = String::from("kind: playlist\nsongs:\n");
        for name in &playlist_names {
            let _ = writeln!(playlist, "- \"{}\"", escape(name));
        }
        std::fs::write(root.join("playlists").join("playlist.yaml"), playlist)?;

        // A second real playlist. `all_songs` is deliberately session-only in
        // the player, so it cannot be used to test persistence -- switching to
        // it and expecting it to survive asserts the opposite of the documented
        // behaviour.
        let mut alternate = String::from("kind: playlist\nsongs:\n");
        for name in playlist_names.iter().rev() {
            let _ = writeln!(alternate, "- \"{}\"", escape(name));
        }
        std::fs::write(root.join("playlists").join("alternate.yaml"), alternate)?;

        let mut config = String::from("# Generated by the mtrack hardware e2e suite.\n");
        config.push_str("songs: songs\n");
        config.push_str("playlist: playlists/playlist.yaml\n");
        config.push_str("playlists_dir: playlists/\n");
        config.push_str("profiles_dir: profiles/\n");
        for (key, value) in &self.extra_config {
            let _ = writeln!(config, "{key}: {value}");
        }
        std::fs::write(root.join("mtrack.yaml"), config)?;

        Ok(Project {
            _dir: dir,
            root,
            grpc_port,
            web_port,
            songs: self.songs,
        })
    }
}

impl Default for ProjectBuilder {
    fn default() -> Self {
        ProjectBuilder::new()
    }
}

/// Writes the fixture type and venue the generated lighting config expects.
///
/// Four fixtures are patched so group constraints with a minimum count have
/// room, and so a show addressing the group drives more than a single DMX
/// address.
fn write_lighting_definitions(root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let fixture_types = root.join("lighting").join("fixture_types");
    let venues = root.join("lighting").join("venues");
    std::fs::create_dir_all(&fixture_types)?;
    std::fs::create_dir_all(&venues)?;

    std::fs::write(
        fixture_types.join("e2e_par.light"),
        format!(
            r#"# Generated by the mtrack hardware e2e suite.
fixture_type "{FIXTURE_TYPE}" {{
  channels: 4
  channel_map: {{
    "dimmer": 1,
    "red": 2,
    "green": 3,
    "blue": 4
  }}
}}
"#
        ),
    )?;

    let mut venue = String::from("# Generated by the mtrack hardware e2e suite.\n");
    let _ = writeln!(venue, "venue \"{VENUE_NAME}\" {{");
    for i in 0..4 {
        let _ = writeln!(
            venue,
            "  fixture \"Par{}\" {FIXTURE_TYPE} @ 1:{} tags [\"wash\", \"front\"]",
            i + 1,
            i * 4 + 1
        );
    }
    venue.push_str("}\n");
    std::fs::write(venues.join("e2e_venue.light"), venue)?;

    Ok(())
}

/// Asks the OS for an unused TCP port.
///
/// There is an unavoidable race between closing the listener and mtrack
/// binding the port; binding to port 0 inside mtrack would avoid it but the
/// port would then not be knowable in advance.
fn free_port_pair() -> std::io::Result<(u16, u16)> {
    // Both listeners are held until both ports are known. Asking twice in
    // sequence can return the same port, and the collision surfaces only as an
    // opaque 45-second readiness timeout.
    let first = TcpListener::bind("127.0.0.1:0")?;
    let second = TcpListener::bind("127.0.0.1:0")?;
    let ports = (first.local_addr()?.port(), second.local_addr()?.port());
    drop(first);
    drop(second);
    Ok(ports)
}
