// Copyright (C) 2026 Michael Wilson <mike@mdwn.dev>
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, version 3.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.
//

//! DMX on the wire, read back from olad (venue-exchange design §15.7).
//!
//! The lighting checks prove the timeline and the effect state; these
//! prove the bytes. Each one patches its own venue — a strobe-capable par,
//! a 16-bit mover with a declared slew limit, a placed mover with a focus
//! point — plays a one-cue show against it, and records what olad is
//! outputting through [`crate::dmx_sink::DmxSink`]. The expected values
//! are computed here, independently, from mtrack's own resolver and
//! pointing math where a hand calculation would only restate them.

use std::time::Duration;

use mtrack::lighting::effects::{aim, Pose};
use mtrack::lighting::types::{ChannelDef, PhysicalRange, PhysicalUnit};
use mtrack::proto::player::v1::{PlayRequest, StopRequest};

use crate::capabilities::Capabilities;
use crate::client::Client;
use crate::dmx_sink::{DmxSink, Frame};
use crate::outcome::CheckOutcome;
use crate::project::{ProfileSpec, ProjectBuilder, LIGHTING_GROUP};
use crate::server::Server;
use crate::songs::{LightingSpec, SongSpec};
use crate::{check, check_eq};

/// The venue these checks select.
const VENUE: &str = "e2e_dmx";
/// The universe the generated profile drives.
const UNIVERSE: u16 = 1;

/// A rich mover in the `.fixture` form: pan 1/2, tilt 3/4, dimmer 5, red 6,
/// with a slew limit only where a check wants one.
fn mover_fixture(max_pan_speed: Option<f64>) -> String {
    let movement = match max_pan_speed {
        Some(speed) => format!("  movement {{ max_pan_speed: {speed}deg/s }}\n"),
        None => String::new(),
    };
    format!(
        "# Generated by the mtrack hardware e2e suite.\n\
         fixture_type \"E2E_Mover\" {{\n  \
           channel \"pan\"    @ 1 fine 2 range -270deg..270deg\n  \
           channel \"tilt\"   @ 3 fine 4 range -135deg..135deg\n  \
           channel \"dimmer\" @ 5\n  \
           channel \"red\"    @ 6\n\
         {movement}}}\n"
    )
}

/// A three-cell RGB pixel bar in the `.fixture` form (design §17.2):
/// dimmer 1, then red/green/blue per cell at 2-4, 5-7, 8-10, the cells
/// 0.3 m apart along the bar.
const PIXEL_BAR: &str = "# Generated by the mtrack hardware e2e suite.\n\
fixture_type \"E2E_PixelBar\" {\n  channel \"dimmer\" @ 1\n  \
cell \"1\" at (-0.3, 0, 0) { channel \"red\" @ 2  channel \"green\" @ 3  channel \"blue\" @ 4 }\n  \
cell \"2\" at (0, 0, 0) { channel \"red\" @ 5  channel \"green\" @ 6  channel \"blue\" @ 7 }\n  \
cell \"3\" at (0.3, 0, 0) { channel \"red\" @ 8  channel \"green\" @ 9  channel \"blue\" @ 10 }\n\
}\n";

/// A par with a hardware strobe channel, in the v1 form: red 1, green 2,
/// blue 3, strobe 4 with the variable range starting at DMX 16.
const STROBE_PAR: &str = "# Generated by the mtrack hardware e2e suite.\n\
fixture_type \"E2E_StrobePar\" {\n  channels: 4\n  channel_map: {\n    \"red\": 1,\n    \
\"green\": 2,\n    \"blue\": 3,\n    \"strobe\": 4\n  }\n  max_strobe_frequency: 20.0\n  \
min_strobe_frequency: 1.0\n  strobe_dmx_offset: 16\n}\n";

/// The pan channel's definition, as the mover above declares it: what the
/// expected bytes are resolved through.
fn pan_def() -> ChannelDef {
    ChannelDef {
        offset: 1,
        fine: Some(2),
        range: Some(PhysicalRange {
            from: -270.0,
            to: 270.0,
            unit: PhysicalUnit::Degrees,
        }),
        functions: Vec::new(),
        mirrors: Vec::new(),
    }
}

fn tilt_def() -> ChannelDef {
    ChannelDef {
        offset: 3,
        fine: Some(4),
        range: Some(PhysicalRange {
            from: -135.0,
            to: 135.0,
            unit: PhysicalUnit::Degrees,
        }),
        functions: Vec::new(),
        mirrors: Vec::new(),
    }
}

/// Degrees the mover's pan bytes mean, for reporting.
fn pan_degrees(frame: &Frame) -> f64 {
    -270.0 + f64::from(frame.value16(1, 2)) / 65535.0 * 540.0
}

/// A project with the given fixture type and venue, and one song whose show
/// is `cues`, addressing the wash group every check's venue tags.
fn dmx_project(
    fixture_file: (&str, String),
    venue: String,
    cues: &str,
) -> Result<crate::project::Project, Box<dyn std::error::Error>> {
    let show = LightingSpec {
        name: "DMX Show".to_string(),
        file: "lighting/dmx.light".to_string(),
        source: format!(
            "# Generated by the mtrack hardware e2e suite.\nshow \"DMX Show\" {{\n{cues}}}\n"
        ),
    };
    let song = SongSpec::tones("DMX Song", "dmx-song", 2, 12.0).with_lighting(show);
    ProjectBuilder::new()
        .profiles(vec![ProfileSpec::detected("01-e2e")
            .with_lighting()
            .with_venue(VENUE)])
        .songs(vec![song])
        .lighting_file(
            &format!("lighting/fixture_types/{}", fixture_file.0),
            &fixture_file.1,
        )
        .lighting_file("lighting/venues/e2e_dmx.venue", &venue)
        .build()
}

/// Starts the player, plays the song, and returns the sink once olad
/// carries the universe.
async fn play_and_sink(
    server: &Server,
    client: &mut Client,
    first_channel: u16,
) -> Result<DmxSink, crate::outcome::CheckError> {
    let caps = Capabilities::get();
    let Some(http_port) = caps.ola_http else {
        return Err(crate::outcome::CheckError::before_assertion(
            "olad's web server is not reachable, so DMX cannot be read back",
        ));
    };
    check_eq!(
        client.subsystem_status("dmx").await?,
        "connected",
        "the DMX engine did not come up.\n--- log ---\n{}",
        server.log()
    );
    let sink = DmxSink::new(http_port);
    sink.ensure_universe(UNIVERSE).await?;
    client.grpc().play(PlayRequest {}).await?;
    client.wait_until_playing(Duration::from_secs(10)).await?;
    sink.wait_for_nonzero(UNIVERSE, first_channel, Duration::from_secs(5))
        .await?;
    Ok(sink)
}

/// A hardware strobe lands in the strobe function's DMX range, not at the
/// raw frequency.
///
/// A par whose strobe function starts at DMX 16 is asked for 10 Hz. The
/// byte must sit inside the function's range — anything below 16 is the
/// "open" range the fixture reads as no strobe — and above what 1 Hz would
/// map to, since 10 Hz is well up the range.
pub async fn strobe_lands_in_the_strobe_function() -> CheckOutcome {
    crate::runner::require_area("dmx-output")?;
    let venue = format!(
        "venue \"{VENUE}\" {{\n  fixture \"Par1\" E2E_StrobePar @ 1:1 tags [\"wash\"]\n}}\n"
    );
    let project = dmx_project(
        ("e2e_strobe_par.light", STROBE_PAR.to_string()),
        venue,
        &format!(
            "    @00:00.000\n    {LIGHTING_GROUP}: static color: \"red\", duration: 10s\n    \
             @00:00.500\n    {LIGHTING_GROUP}: strobe frequency: 10, duration: 8s, layer: foreground\n"
        ),
    )?;
    let server = Server::start(&project).await?;
    let mut client = Client::connect(&server).await?;
    let sink = play_and_sink(&server, &mut client, 1).await?;

    let frame = sink
        .wait_for_nonzero(UNIVERSE, 4, Duration::from_secs(5))
        .await?;
    client.grpc().stop(StopRequest {}).await?;

    let strobe = crate::sabotage::pick(frame.channel(4), 5);
    crate::outcome::record(format!(
        "strobe byte {strobe} (function 16..255), red {}",
        frame.channel(1)
    ));
    check!(
        strobe >= 16,
        "the strobe byte {strobe} is below the function's start (16): the fixture reads \
         that as open, not strobing"
    );
    // 10 Hz in a 1..20 Hz range resolved in period space lands in the upper
    // half of the function; 1 Hz would sit at 16.
    check!(
        strobe > 100,
        "the strobe byte {strobe} is far too low for 10 Hz on a 1..20 Hz function"
    );
    server.check_clean_log(&[])?;
    Ok(())
}

/// A slow sweep across a 16-bit channel never steps the coarse byte back
/// across a fine rollover, and advances in small steps.
pub async fn a_slow_sweep_is_continuous_across_sixteen_bits() -> CheckOutcome {
    crate::runner::require_area("dmx-output")?;
    let venue = format!(
        "venue \"{VENUE}\" {{\n  fixture \"M1\" E2E_Mover @ 1:1 tags [\"wash\"] position (0, 3, 4) rotation (0, 0, 180)\n}}\n"
    );
    let project = dmx_project(
        ("e2e_mover.fixture", mover_fixture(None)),
        venue,
        &format!(
            "    @00:00.000\n    {LIGHTING_GROUP}: static red: 100%, duration: 10s\n    \
             @00:00.000\n    {LIGHTING_GROUP}: move from_pan: -60deg, pan: 60deg, tilt: 0deg, duration: 6s, easing: linear\n"
        ),
    )?;
    let server = Server::start(&project).await?;
    let mut client = Client::connect(&server).await?;
    let sink = play_and_sink(&server, &mut client, 6).await?;

    let frames = sink
        .record(UNIVERSE, Duration::from_secs(3), Duration::from_millis(25))
        .await?;
    client.grpc().stop(StopRequest {}).await?;

    let values: Vec<u16> = frames.iter().map(|f| f.value16(1, 2)).collect();
    let values = crate::sabotage::pick(values.clone(), {
        // A step backwards (or, from 0, a wild jump): either fails.
        let mut broken = values.clone();
        if broken.len() > 2 {
            broken[2] = broken[1].wrapping_sub(1);
        }
        broken
    });
    let distinct: std::collections::BTreeSet<u16> = values.iter().copied().collect();
    crate::outcome::record(format!(
        "{} frames, {} distinct pan values, {:.1}° → {:.1}°",
        values.len(),
        distinct.len(),
        pan_degrees(&frames[0]),
        pan_degrees(frames.last().unwrap())
    ));
    check!(
        distinct.len() >= 20,
        "a 3 s window of a 120° sweep produced only {} distinct 16-bit pan values; \
         the fine byte is not moving",
        distinct.len()
    );
    let mut coarse_prev = values[0] >> 8;
    for pair in values.windows(2) {
        let (a, b) = (pair[0], pair[1]);
        check!(
            b >= a,
            "the pan value stepped backwards: {a} → {b} (fine rollover)"
        );
        // 120° over 6 s at 40 Hz is ~0.5°/frame ≈ 61 LSB; allow a slow poll.
        check!(
            b - a <= 2048,
            "the pan value jumped {} LSB in one frame; that is not a slow sweep",
            b - a
        );
        let coarse = b >> 8;
        check!(
            coarse >= coarse_prev,
            "the coarse byte stepped backwards across a rollover"
        );
        coarse_prev = coarse;
    }
    server.check_clean_log(&[])?;
    Ok(())
}

/// A declared slew limit holds a sweep to the declared speed.
///
/// The mover is asked to jump 180° in a tenth of a second while declaring
/// 90°/s, so after a second it must be near 90° along, not at the target.
pub async fn a_declared_slew_limit_holds_the_sweep() -> CheckOutcome {
    crate::runner::require_area("dmx-output")?;
    let venue = format!(
        "venue \"{VENUE}\" {{\n  fixture \"M1\" E2E_Mover @ 1:1 tags [\"wash\"] position (0, 3, 4) rotation (0, 0, 180)\n}}\n"
    );
    let project = dmx_project(
        ("e2e_mover.fixture", mover_fixture(Some(90.0))),
        venue,
        &format!(
            "    @00:00.000\n    {LIGHTING_GROUP}: static red: 100%, duration: 10s\n    \
             @00:00.000\n    {LIGHTING_GROUP}: move pan: -90deg, tilt: 0deg, duration: 100ms\n    \
             @00:01.000\n    {LIGHTING_GROUP}: move pan: 90deg, tilt: 0deg, duration: 100ms\n"
        ),
    )?;
    let server = Server::start(&project).await?;
    let mut client = Client::connect(&server).await?;
    let sink = play_and_sink(&server, &mut client, 6).await?;

    // Sample around 1.9 s into the song: 0.9 s after the jump was asked,
    // the mover has had time for ~80° of its 180°.
    let frames = sink
        .record(
            UNIVERSE,
            Duration::from_millis(2600),
            Duration::from_millis(50),
        )
        .await?;
    client.grpc().stop(StopRequest {}).await?;

    // Frames are relative to when the sink saw the first nonzero red, which
    // is within a few frames of 0 s.
    let at = |secs: f64| {
        frames
            .iter()
            .min_by(|a, b| {
                let da = (a.at.duration_since(frames[0].at).as_secs_f64() - secs).abs();
                let db = (b.at.duration_since(frames[0].at).as_secs_f64() - secs).abs();
                da.total_cmp(&db)
            })
            .unwrap()
    };
    let mid = pan_degrees(at(1.8));
    let late = pan_degrees(at(2.5));
    let mid = crate::sabotage::pick(mid, 90.0);
    crate::outcome::record(format!(
        "pan at ~1.8 s: {mid:.1}° (asked for +90 at 1.0 s, limit 90°/s); at ~2.5 s: {late:.1}°"
    ));
    check!(
        (-40.0..=40.0).contains(&mid),
        "0.8 s after a 180° jump at 90°/s the pan should be near -18°..+0°, allowing for \
         timing; it was {mid:.1}°"
    );
    check!(
        late > mid,
        "the mover stopped short instead of continuing toward the goal after its effect ended"
    );
    server.check_clean_log(&[])?;
    Ok(())
}

/// A focus point resolves to the pan and tilt the pointing math predicts,
/// through the fixture's placement and mounting in the venue.
pub async fn a_focus_point_resolves_through_the_venue() -> CheckOutcome {
    crate::runner::require_area("dmx-output")?;
    let position = [-2.0, 3.5, 4.2];
    let rotation = [0.0, 0.0, 180.0];
    let drummer = [0.0, 2.8, 1.4];
    let venue = format!(
        "venue \"{VENUE}\" {{\n  fixture \"M1\" E2E_Mover @ 1:1 tags [\"wash\"] position (-2, 3.5, 4.2) rotation (0, 0, 180)\n  focus \"drummer\" (0, 2.8, 1.4)\n}}\n"
    );
    let project = dmx_project(
        ("e2e_mover.fixture", mover_fixture(None)),
        venue,
        &format!(
            "    @00:00.000\n    {LIGHTING_GROUP}: static red: 100%, duration: 10s\n    \
             @00:00.000\n    {LIGHTING_GROUP}: move focus: \"drummer\", duration: 200ms\n"
        ),
    )?;
    let server = Server::start(&project).await?;
    let mut client = Client::connect(&server).await?;
    let sink = play_and_sink(&server, &mut client, 6).await?;
    tokio::time::sleep(Duration::from_millis(800)).await;
    let frame = sink.read(UNIVERSE).await?;
    client.grpc().stop(StopRequest {}).await?;

    // Worked by hand (design §18.2), not by mtrack's own pointing math:
    // d = (2, −0.7, −2.8); the 180° yaw flips x and y → (−2, 0.7, −2.8),
    // unit (−0.5675, 0.1986, −0.7994). tilt = acos(0.7994) = 37.12°,
    // pan = atan2(0.5675, 0.1986) = 70.71°. Over ±270° and ±135° on 16
    // bits: pan (340.71/540)·65535 = 41349, tilt (172.12/270)·65535 = 41777.
    let expected = Pose {
        pan: 70.71,
        tilt: 37.12,
    };
    let (want_pan, want_tilt): (u16, u16) = (41349, 41777);
    assert!(
        (aim(position, rotation, drummer).pan - expected.pan).abs() < 0.01
            && (aim(position, rotation, drummer).tilt - expected.tilt).abs() < 0.01,
        "the hand derivation and the pointing math disagree"
    );
    let got_pan = crate::sabotage::pick(frame.value16(1, 2), want_pan.wrapping_add(5000));
    let got_tilt = frame.value16(3, 4);
    crate::outcome::record(format!(
        "pointing math: pan {:.2}° tilt {:.2}° → 16-bit {want_pan}/{want_tilt}; wire {got_pan}/{got_tilt}",
        expected.pan, expected.tilt
    ));
    check!(
        got_pan.abs_diff(want_pan) <= 2,
        "pan on the wire ({got_pan}) is not the pointing math's ({want_pan}) for the drummer"
    );
    check!(
        got_tilt.abs_diff(want_tilt) <= 2,
        "tilt on the wire ({got_tilt}) is not the pointing math's ({want_tilt}) for the drummer"
    );
    server.check_clean_log(&[])?;
    Ok(())
}

/// A `per: cell` chase runs along a pixel bar's cells on the wire: one
/// cell's red byte up while the others are down, every cell taking a
/// turn — over a bed that keeps the bar's dimmer up throughout. The same
/// show without `per: cell` lights the whole bar as one (design §17.3).
pub async fn a_per_cell_chase_runs_along_the_bar() -> CheckOutcome {
    crate::runner::require_area("dmx-output")?;
    let venue = format!(
        "venue \"{VENUE}\" {{\n  fixture \"Bar1\" E2E_PixelBar @ 1:1 tags [\"wash\"] position (0, 3, 4) rotation (0, 0, 180)\n}}\n"
    );
    let project = dmx_project(
        ("e2e_pixel_bar.fixture", PIXEL_BAR.to_string()),
        venue,
        &format!(
            "    @00:00.000\n    {LIGHTING_GROUP}: static color: \"red\", dimmer: 100%, duration: 10s\n    \
             @00:00.000\n    {LIGHTING_GROUP}: chase pattern: linear, speed: 2.0, direction: left_to_right, transition: snap, per: cell, duration: 4s, layer: midground\n    \
             @00:05.000\n    {LIGHTING_GROUP}: chase pattern: linear, speed: 2.0, direction: left_to_right, transition: snap, duration: 4s, layer: midground\n"
        ),
    )?;
    let server = Server::start(&project).await?;
    let mut client = Client::connect(&server).await?;
    let sink = play_and_sink(&server, &mut client, 1).await?;

    // Two seconds of the per-cell chase at 2 Hz: four passes over three
    // cells, sampled faster than a step.
    let per_cell = sink
        .record(
            UNIVERSE,
            Duration::from_millis(2000),
            Duration::from_millis(40),
        )
        .await?;
    // Then, past 5 s, the same chase per fixture.
    tokio::time::sleep(Duration::from_millis(3200)).await;
    let per_fixture = sink
        .record(
            UNIVERSE,
            Duration::from_millis(1000),
            Duration::from_millis(40),
        )
        .await?;
    client.grpc().stop(StopRequest {}).await?;

    let reds = |frame: &Frame| [frame.channel(2), frame.channel(5), frame.channel(8)];
    let lit = |frame: &Frame| -> Vec<usize> {
        reds(frame)
            .iter()
            .enumerate()
            .filter(|(_, v)| **v > 200)
            .map(|(i, _)| i)
            .collect()
    };
    let single: Vec<&Frame> = per_cell.iter().filter(|f| lit(f).len() == 1).collect();
    let mut seen: Vec<usize> = single.iter().flat_map(|f| lit(f)).collect();
    seen.sort();
    seen.dedup();
    let seen = crate::sabotage::pick(seen, vec![0]);
    let whole = per_fixture.iter().filter(|f| lit(f).len() == 3).count();
    crate::outcome::record(format!(
        "per cell: {} of {} frames had exactly one cell lit, cells seen {seen:?}; per fixture: \
         {whole} of {} frames had all three lit; dimmer stayed at {}",
        single.len(),
        per_cell.len(),
        per_fixture.len(),
        per_cell
            .iter()
            .skip(8)
            .map(|f| f.channel(1))
            .min()
            .unwrap_or(0)
    ));
    check!(
        single.len() * 2 > per_cell.len(),
        "with `per: cell` most frames should show exactly one lit cell; {} of {} did",
        single.len(),
        per_cell.len()
    );
    check_eq!(
        seen,
        vec![0, 1, 2],
        "every cell should take its turn under a per-cell chase"
    );
    // The recording starts at the first nonzero frame, while the engine's
    // dim-speed smoothing is still ramping the bed up: judge the dimmer
    // once the ramp is over.
    let settled: Vec<&Frame> = per_cell
        .iter()
        .filter(|f| f.at.duration_since(per_cell[0].at) > Duration::from_millis(300))
        .collect();
    check!(
        !settled.is_empty() && settled.iter().all(|f| f.channel(1) == 255),
        "the bed's dimmer, which no cell owns, should stay up once settled; it read {:?}",
        settled.iter().map(|f| f.channel(1)).min()
    );
    check!(
        whole > 0 && per_fixture.iter().all(|f| lit(f).len() != 1),
        "without `per: cell` the chase treats the bar as one fixture: every frame should light \
         all three cells or none, never exactly one; {whole} of {} lit all three",
        per_fixture.len()
    );
    server.check_clean_log(&[])?;
    Ok(())
}
